sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn
script: yarn ci
branches:
  only: master
